### PR TITLE
MTGA_Draft_Tool_V0315

### PR DESCRIPTION
**Pull request by unrealities**
* Improve autocomplete on Card Compare
* Add Git issues
* Re-Added Wheel Display Option

### CODE REVIEW

**Comment by gpofcher** [comment]
It's great to see this tool getting regular updates again—thank you!

After updating the windows executable to 3.15 via the autoupdater, I get this error on launch:

```
Traceback (most recent call last):
  File "main.py", line 11, in <module>
  File "main.py", line 8, in main
  File "src\overlay.py", line 53, in start_overlay
  File "src\overlay.py", line 410, in __init__
  File "src\overlay.py", line 738, in __set_os_configuration
  File "tkinter\__init__.py", line 2430, in __getattr__
AttributeError: '_tkinter.tkapp' object has no attribute 'tkinter'
```

(I couldn't figure out how to submit this as an issue—this seemed like the next best place.)

**Comment by unrealities** [comment]
Thank you for the feedback. I don't usually use this on Windows, I just do the build to keep it updated. I'll take a look and see if I can reproduce the issue. 

It's nice seeing people using the tool!

**Comment by gpofcher** [comment]
Seems to be fixed with the latest update—thanks!
